Небольшая запутка
Вот что сказал компилятор:
defined class A
a1: A = A@17bd67e7
a2: A = A@65cf0468
b1: a1.B = A$B@3b5d8fb7
b2: a2.B = A$B@44a1e9db
a1.b: Option[a1.B] = Some(A$B@3b5d8fb7)
fp.scala:36: error: type mismatch;
 found   : a1.B
 required: a2.B
a2.b = Some(b1)